
#General settings
[general]

	[general."Skullfire Sword"]
		#DropChange
		#Range: 0 ~ 100
		dropChange = 100

	[general."Infinity Armor"]
		#NightVision
		nightVision = true
		#ClearBadEffect
		clearBadEffect = true

